### ISSUE TITLE
Request to make program reject negative numbers as internal marks.

### ISSUE THREAD

**Issue by Anish-M-code** [gowtham758550/Anna-university-reg-17-grade#1]
![negative](https://user-images.githubusercontent.com/58029804/87856502-34750c80-c90f-11ea-8ec1-adad689a7617.png)
Program currently accepts negative marks as input but this doesn't happened in real life. Please fix this silly bug soon...

**Comment by gowtham758550** [comment]
![Screenshot_20200718-224913](https://user-images.githubusercontent.com/63159252/87858091-f4328000-c948-11ea-9422-6f69869d6472.png)
Issue is solved now🤠.
Even it is a simple logic.
Issues are always welcome 👍.
